# -*- coding: utf-8 -*-
"""csv_merge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1llAACkBhz5n9sWLXErcpYw7HsOzWkkna
"""

!pip install pandas

import os
import glob
import pandas as pd

# Current directory
path = os.getcwd()

# Find all .csv files in the directory
all_files = glob.glob("content/*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=1)
    li.append(df)

if len(li) > 0:
    frame = pd.concat(li, axis=0, ignore_index=True)
    frame.to_csv("content/combined.csv", index=False)

# Get the current directory
path = os.getcwd()

# Get a list of all the csv files in the directory
all_files = sorted(glob.glob(os.path.join(path, "*.csv")))

# Counter for the new filenames
count = 1

# Rename each file
for filename in all_files:
    new_name = os.path.join(path, f"{count}.csv")
    os.rename(filename, new_name)
    count += 1

print("CSV files renamed successfully!")

import os
import pandas as pd
import glob

# Get the current directory
path = os.getcwd()

# Get a list of all the csv files in the directory
all_files = glob.glob(os.path.join(path, "*.csv"))

# Create an empty list to store the dataframes
dfs = []

# Read each csv file and append it to the dfs list
for filename in all_files:
    df = pd.read_csv(filename, index_col=None)
    dfs.append(df)

# Concatenate all the dataframes in the dfs list
merged_df = pd.concat(dfs, ignore_index=True)

# Save the merged dataframe to a new csv file
merged_df.to_csv("merged.csv", index=False)

print("CSV files merged successfully into merged.csv")

