# -*- coding: utf-8 -*-
"""enhance_image.ipynb

Automatically generated by Colab.

"""

!pip install PyPDF2

import cv2

def enhance_image(input_path, output_path):
    # Read the Image
    image = cv2.imread(input_path, cv2.IMREAD_ANYCOLOR)  # If it's a grayscale image

    # Basic Cleanup
    # Use the fastNlMeansDenoising function to remove noise
    denoised = cv2.fastNlMeansDenoising(image, None, 30, 7, 21)

    # Adjust Brightness and Contrast
    adjusted = cv2.convertScaleAbs(denoised, alpha=1, beta=10)  # Tweak alpha (contrast) and beta (brightness) as necessary

    # Enhance Details
    # Use the GaussianBlur and addWeighted functions to sharpen the image
    blurred = cv2.GaussianBlur(adjusted, (0,0), 3)
    sharpened = cv2.addWeighted(adjusted, 1.5, blurred, -0.5, 0)

    # Save the Enhanced Image
    cv2.imwrite(output_path, sharpened)

# Usage
input_path = '/content/Sam24.jpg'
output_path = 'enhanced_image.jpg'
enhance_image(input_path, output_path)

